"""adding is_seen to film table

Revision ID: 57c759980a15
Revises: 
Create Date: 2024-06-16 04:35:08.175651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57c759980a15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bloodyfilms', sa.Column('is_seen', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bloodyfilms', 'is_seen')
    # ### end Alembic commands ###
