"""add shown_films to user table and delete is_seen from bloodyfilms

Revision ID: dd03acb8f402
Revises: f43d249e8e6a
Create Date: 2024-06-30 18:47:44.815809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd03acb8f402'
down_revision = 'f43d249e8e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bloodyfilms', 'is_seen')
    op.add_column('users', sa.Column('shown_films', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'shown_films')
    op.add_column('bloodyfilms', sa.Column('is_seen', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
