"""add user_character to user table

Revision ID: eb36b83939cd
Revises: 57c759980a15
Create Date: 2024-06-28 21:34:53.089411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb36b83939cd'
down_revision = '57c759980a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_character', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_character')
    # ### end Alembic commands ###
