"""add coins to user table

Revision ID: f43d249e8e6a
Revises: eb36b83939cd
Create Date: 2024-06-30 16:00:29.951241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43d249e8e6a'
down_revision = 'eb36b83939cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('coins', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'coins')
    # ### end Alembic commands ###
